site_name: Nástroje NoPlaceLeft

nav:
  - Úvod: index.md
  - Discovery: discovery.md
  - Boží rodina: bozi-rodina.md

plugins:
  - search

theme:
  name: material
  language: cs
  palette:
    - scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  features:
    - content.tooltips
  icon:
      annotation: material/clock-outline
      logo: material/hammer-wrench
  favicon: favicon.ico

extra_css:
  - style.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  generator: false
