site_name: Kroky s Ježíšem
site_dir: ../../dist

nav:
  - Meeting of God's family: index.md
  - Vision strengthening: posileni-vize.md
  - Discovery: https://en.discoverybible.cz
  - Cards for printing: karticky-k-tisku.md

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Light mode
  features:
    - content.tooltips
    - grids
    - navigation.instant
    - navigation.instant.prefetch
  icon:
      annotation: material/clock-outline
      logo: material/book-open-blank-variant-outline
  favicon: favicon.ico
  custom_dir: overrides

extra_css:
  - https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css
  - stylesheets/style.css
  - stylesheets/print.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js
  - javascripts/main.js

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/icons
extra:
  analytics: true
  generator: false
